### ISSUE TITLE
在dev模式下扩展不能向webview发送消息

### ISSUE THREAD

**Issue by frg2089** [tomjs/vscode-extension-webview#1]
这里看起来会直接丢弃掉来自扩展的消息

https://github.com/tomjs/vscode-extension-webview/blob/48f24d781dacf78e88ee1f7a65842026a6e4fa65/src/template.html#L76-L91

**Comment by tomgao365** [comment]
是的，之前没考虑的这个，我加一下。

**Comment by tomgao365** [comment]
@frg2089 加了extension的postMessage支持，试试最新的版本

**Comment by tomgao365** [comment]
[v1.2.0](https://github.com/tomjs/vscode-extension-webview/releases/tag/v1.2.0) 已添加支持
