### ISSUE TITLE
How to debug webview using vscode brakepoints ? 

### ISSUE THREAD

**Issue by MindsightsAI** [tomjs/vscode-extension-webview#2]

**Comment by tomgao365** [comment]
Hi, @MindsightsAI 
Whether this  [example](https://github.com/tomjs/vscode-extension-webview/blob/main/examples/vue/.vscode/launch.json) is what you want

**Comment by tomgao365** [comment]
If you use vite, you can try this  [vite-plugin-vscode](https://github.com/tomjs/vite-plugin-vscode) plugin
