### ISSUE TITLE
当把webview页面注册为activitybar时，由于默认添加了csp设置，会导致webview页面受限无法发起请求

### ISSUE THREAD

**Issue by programmermark** [tomjs/vscode-extension-webview#3]
当把webview页面注册为activitybar时，由于默认添加了csp设置，会导致webview页面受限无法发起请求。

注册为activitybar时，设置csp只能通过在html字符串中手动设置；如果是在插件中无法通过参数控制，会导致不肯避免的csp问题。

```
head.insertAdjacentHTML(
      'afterbegin',
      `\n<meta http-equiv="Content-Security-Policy" content="default-src 'none'; style-src {{cspSource}} 'unsafe-inline'; script-src 'nonce-{{nonce}}' 'unsafe-eval';">`,
    );
```
可以在 getWebviewHtml中扩展一个参数，便于控制。

**Comment by tomgao365** [comment]
@programmermark 你好，你说的是 `production ` 时的情况吗？这个库是为了 vue/react 这些框架开发时实现热更新的。
如果是生产的话，可以按需要自己设置输出的 html。
如果使用 vite 的话，可以看看 [@tomjs/vite-plugin-vscode](https://github.com/tomjs/vite-plugin-vscode) 这个插件，开发用了 iframe，可以像web开发一样；生产的时候会根据输出内容设置 csp

**Comment by tomgao365** [comment]
@programmermark 你想自定义 csp 吗？我加个 csp 参数用于自行定义

**Comment by programmermark** [comment]
我issue发错位置了。
